ecmwf-ifs/field_api

CMakeLists.txt
Readme.md
tests/CMakeLists.txt

Adding two new compilation options: ENABLE_SINGLE_PRECISION and ENABLE_DOUBLE_PRECISION to let the user choose to disable compilation in dp or sp.
A use case for these modification is, for instance,  when building field_api with a version of fiat that has only been compiled in double precision.
By default, both are enabled.

Let the user disable sp or dp compilation

---

tests/CMakeLists.txt
tests/check_gpu_num.F90

This PR implements the enhancement highlighted in #4. In a nutshell, GPU specific tests are only built if OpenACC is found.

Separate GPU specific tests

---

tests/cpu_to_gpu.F90
tests/cpu_to_gpu_delayed_init_value.F90
tests/cpu_to_gpu_init_value.F90
tests/gather_scatter.F90
tests/get_view_get_device_data.F90
tests/init_owner_delayed_gpu.F90
tests/init_owner_delayed_init_debug_value.F90
tests/init_owner_delayed_init_value.F90
tests/init_owner_init_debug_value.F90
tests/init_owner_init_debug_value_gpu.F90
tests/init_owner_init_delayed_debug_value_gpu.F90
tests/init_owner_init_delayed_value_gpu.F90
tests/init_owner_init_value.F90
tests/main.F90
tests/no_transfer_get_device.F90
tests/no_transfer_get_host.F90

A very small PR that adds:
- missing copyright headers
- small fixes to the main.F90 unit-test

Add missing copyright headers

---

field_RANKSUFF_data_module.fypp

In v0.2.1 and v0.2.2, the dummy arguments `HST,DEV` in the `COPY_DIM_CONTIGUOUS` subroutine had the pointer attribute. This was accidentally removed (apologies!) in the CUDA PR.
Without the `POINTER` attribute, the runtime reshapes the dummy args so that the LBOUNDS are always 1, rather than the true LBOUNDS of `SELF%PTR` and `SELF%DEVPTR`. This doesn't cause any problems in most cases, which explains why this went unnoticed. The only case it fails for is when `CHILD%DEVPTR` is a discontiguous slice of `GANG%DEVPTR` and we try and do per-child copies.
Even though we don't plan on introducing per-child copies to the master branch in the near future, I still think this change should be reverted because:
1. It was introduced by accident
2. WIthout it, the explicit loops from LBOUNDS(DEV) to …

Restore POINTER attribute to COPY_DIM_CONTIGUOUS dummy args

---

.github/workflows/fieldapi_gnu.yml
.github/workflows/fieldapi_intel.yml
.github/workflows/fieldapi_intel_classic.yml
.github/workflows/fieldapi_intel_modern.yml

Downloads and install the last intel compilers from their official repository and run the field_api tests.
Note that it uses the new icx and ifx compilers instead of the old icc and ifort compilers.

add continous integration with the last intel compilers

---

field_RANKSUFF_util_module.fypp

field_RANKSUFF_util_module.fypp was not generating utilities for 1D fields. This PR solves this issue.

Generate utilities for 1D fields

---

field_RANKSUFF_array_util_module.fypp

Some generic interfaces (LOAD, SAVE, etc.) are empty : 
```
INTERFACE LOAD
END INTERFACE
```
This is a problem with PGI, which has been reported.  I suggest we just do not generate these empty generic interfaces.

Disable empty generic interfaces

---

CMakeLists.txt

If openacc is disabled, then we are not limited by the `!$acc declare create` statements in field_RANKSUFF_access_module and we can link libfield_api statically. This PR adds this functionality.

Optional dynamic linking

---

field_RANKSUFF_data_module.fypp
tests/CMakeLists.txt
tests/test_sizeof.F90

A small bug-fix that was discovered with IFS regression testing. The incorrect size of the copy buffer was triggering `cuMemcpyHtoDAsync` errors, which are fixed with this.
Many thanks to @awnawab for debugging help and @pmarguinaud for providing the test.

Bugfix: Correct size for non-CUDA device copies

---

CMakeLists.txt
cmake/field_api-import.cmake.in
cmake/field_api_compile_options.cmake
cmake/field_api_fetchcontent_fypp.cmake
tests/CMakeLists.txt

This PR contributes three small CMake fixes:
1. If enabled, cuda is now linked publicly, just like OpenACC. This has the advantage that an externally built/installed FIELD_API with openacc and/or cuda can be linked to shared library targets even if they do not do any offload.
2. A cmake import configuration is added, which exports vital information about the FIELD_API build configuration to any cmake project that issues `find_project( field_api ... )`.
3. FIELD_API can now also optionally use the fypp installation included in fckit's virtual python environment.

Various cmake fixes

---

CMakeLists.txt
field_RANKSUFF_array_module.fypp
tests/CMakeLists.txt
tests/test_field_array.F90

This PR adds a check so that FIELD_ARRAY does not wrap 0-sized fields. It also adds the `P_FIELD` pointer member which we need for our Loki recipes to move from thread-local to shared data structures. Finally, there is a small bug fix to the fypp detection mechanism.

FIELD_ARRAY: safely handle 0-sized fields

---

field_RANKSUFF_array_module.fypp

This PR mops up something I previously missed. The global pointer needs the contiguous attribute so that it can be correctly registered in the OpenACC map via `!$acc enter data attach`.

FIELD_ARRAY: add contiguous attribute to global pointer

---

CMakeLists.txt
field_RANKSUFF_access_module.fypp
field_RANKSUFF_module.fypp

For apps like CLOUDSC, FIELD_API also supports compilation without FIAT. This PR re-enables that functionality.

Fix compilation in absence of FIAT

---

CMakeLists.txt
tests/CMakeLists.txt

_Note: This is an alternative implementation to #54 that solves the same problem._
Recap of the problem: Due to FIELD API exporting the OpenACC target via PUBLIC, we cannot select upstream for which component to enable OpenACC offload and for which to disable it. 
In this implementation we downgrade this to exporting OpenACC via INTERFACE so that all header paths are propagated, but OpenACC can still be selected by the user component. This, in turn requires the internal tests to now explicitly link against OpenACC and set the `-cuda` flag, if enabled (thanks to @awnawab for the fixes; I copied them from #54 ). 
@dareg Could you please confirm that this is backward compatible with the MF build system?  
Edit: Tested and confirmed working with H24 regression testing.

CMake: Export OpenACC symbols via INTERFACE target linking

---

CMakeLists.txt

This PR fixes the problem identified in #55 and enables FIELD_API to use the fckit provided fypp even in the absence of `FCKIT_VENV` (which requires python3 >= 3.8).

Use fckit contributed fypp even in absence of FCKIT_VENV

---

CMakeLists.txt

This triggers the CMake search for the programming model only if the corresponding ecbuild option is activated.

CMake: Only search for OpenACC if the corresponding option is active

---

CMakeLists.txt
tests/CMakeLists.txt

A small bugfix PR to fix the propagation of acc link flags to executables linking against FIELD_API. This will allow an openacc enabled FIELD_API to be used with a target even if that doesn't link against OpenACC.

Fix propagation of ACC link flags

---

.github/workflows/build-hpc.yml
.github/workflows/label-public-pr.yml

This PR adds the ability to run the hpc-ci on PRs filed from forks. Importantly, this will only run once a maintainer has added the "approved-for-ci" label. Any further pushes to the PR will remove the label, and it will have to be manually re-added to re-run the hpc-ci. Thanks a lot @samhatfield for showing us how to do this 🙏

Run hpc-ci on PRs filed from forks

---

.github/workflows/build-hpc.yml

A fix to ensure the correct branch is checked out when a PR is filed from a fork.

Fix hpc-ci for PRs filed from forks

---

src/core/dev_alloc_module.fypp
tests/CMakeLists.txt
tests/test_0_sized_transfer.F90

A small PR to add checks to enable safe transfers of data between host and device of 0-sized allocations.

Safely transfer 0-sized allocations

---

CMakeLists.txt
Readme.md
cmake/field_api_find_fiat_modules.cmake
src/debug/CMakeLists.txt

(Copy of #117)
I found the current logic behind optional FIAT dependence of Field API a bit misleading. I propose to make FIAT a required dependence, except if the path to the FIAT components is explictly specified, as it is done in CLOUDSC. Otherwise, it is suggested to the user that it is sufficient to provide the path to the three file listed to compiled FA. However, providing the path to the FIAT source doesn't work, because FIAT version of these files is way more complex that the stripped source of CLOUDSC. In conclusion, FIAT should be explicitly required by FA except if the user knows what he/she is doing and decides otherwise.
The code seems to compile in both scenarios (with FIAT and with path to the CLOUDSC-prepared sources) with NVHPC, and as a part of the CLOUDSC bundle.

Rearranged logic to require FIAT by default, except if explicitely demanded.
